---
owner: buape
repo: status
sites:
  - name: "Kiai: Bot"
    url: http://host.buape.com:6677
    assignees:
      - net-tech
      - thewilloftheshadow
      - tm21cy
      - Codeize
    expectedStatusCodes:
      - 200
      - 302
  - name: "Kiai: Website"
    url: https://www.kiaibot.com
    assignees:
      - thewilloftheshadow
      - Codeize
  - name: "Kiai: API"
    url: https://api.kiaibot.com
    assignees:
      - net-tech
      - thewilloftheshadow
      - tm21cy
      - Codeize
  - name: "Kiai: Docs"
    url: https://docs.kiaibot.com
    assignees:
      - thewilloftheshadow
      - Codeize
  - name: Unleash
    url: https://unleash.kiaibot.com
  - name: go.buape.com (Link Shortener)
    url: https://go.buape.com
  - name: Buape Files
    url: https://files.buape.com
  - name: Buape CDN
    url: https://cdn-raw.buape.com/buape_circle.png
  - name: "Server: Buape1"
    url: host.buape.com
    port: 22
    check: tcp-ping
status-website:
  cname: status.buape.com
  logoUrl: https://cdn.buape.com/buape_circle.png
  name: Buape Status
  theme: night
  introTitle: Welcome to the Buape Status page.
  introMessage: This page combines the status of all of Buape Studio's products
    into one easy-to-check page!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/buape
    - title: Discord
      href: https://go.buape.com
assignees:
  - thewilloftheshadow
  - tm21cy
